### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by nads205** [sebafo/frontdoor-container-apps#11]
@sebafo in the readme it states that this is _only sample code and not production ready_. 

What is required for production readiness?

**Comment by sebafo** [comment]
The official answer is to use an Application Gateway between FrontDoor and ACA. There is no official support for this kind of setup, and for workload profiles (dedicated tier) this isn't working at all. That the reason why I want to keep the "not production ready" note.
Source: https://github.com/microsoft/azure-container-apps/issues/402#issuecomment-1599437712
