### ISSUE TITLE
State required Azure providers

### ISSUE THREAD

**Issue by SomeBdyElse** [sebafo/frontdoor-container-apps#3]
For this deployment to succeed, the following Azure providers need to be registered: 

```
az provider register --wait --namespace Microsoft.App
az provider register --wait --namespace Microsoft.ContainerService
az provider register --wait --namespace Microsoft.Cdn
```

Apparently, providers can not be registered by an ARM/bicep template. I suggest to add the above lines to the deploy.sh or to the README.md .

**Comment by sebafo** [comment]
Oh yes, those providers are required to deploy Container Apps. I'm going to add them, thx!

**Comment by SomeBdyElse** [comment]
If you add them to `deploy.sh` I suggest to use the ` --wait` switch. I altered the lines in my original issue description.
